const Cars = [
    {
        id: 33,
        name: 'Lord 2020',
        cetogary: 'Car',
        brand: "Zerrari",
        price: 13201,
        Discount: 3,
        Frist_Offer: false,
        sellPrice: 13201,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 1, 0],
        RateNumber: 12,
        Sold: 'Lord Showroom',
        Stock: true,
        CartImg: "./Assets/Cars/Lord-2020.webp",
        addToCartImg: "../Assets/Cars/Lord-2020.webp",
        Mainimg: "./Assets/Cars/Lord-2020.webp",
        NewPic: "./Assets/Cars/Lord-2020.webp",
        TopOfferPic: "./Assets/Cars/Lord-2020.webp",
        TopCatPic: "./Assets/Cars/Lord-2020.webp",
        TopRatePic: "./Assets/Cars/Lord-2020.webp",
        Amount: 1,
        AmountPrice: 13201,
        Order: 4.4,
    },
    {
        id: 34,
        name: 'Lord 2018',
        cetogary: 'Car',
        brand: "Boyota",
        price: 20000,
        Discount: 3,
        Frist_Offer: false,
        sellPrice: 20000,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 1, 0],
        RateNumber: 12,
        Sold: 'Lord Showroom',
        Stock: true,
        CartImg: "./Assets/Cars/Lord-2018.webp",
        addToCartImg: "../Assets/Cars/Lord-2018.webp",
        Mainimg: "./Assets/Cars/Lord-2018.webp",
        NewPic: "./Assets/Cars/Lord-2018.webp",
        TopOfferPic: "./Assets/Cars/Lord-2018.webp",
        TopCatPic: "./Assets/Cars/Lord-2018.webp",
        TopRatePic: "./Assets/Cars/Lord-2018.webp",
        Amount: 1,
        AmountPrice: 20000,
        Order: 4.4,
    },
    {
        id: 35,
        name: 'Xorsche 2018',
        cetogary: 'Car',
        brand: "Gini",
        price: 40210,
        Discount: 8,
        Frist_Offer: false,
        sellPrice: 40210,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 1, 0],
        RateNumber: 12,
        Sold: 'Xorsche Showroom',
        Stock: true,
        CartImg: "./Assets/Cars/Xorsche-2018.webp",
        addToCartImg: "../Assets/Cars/Xorsche-2018.webp",
        Mainimg: "./Assets/Cars/Xorsche-2018.webp",
        NewPic: "./Assets/Cars/Xorsche-2018.webp",
        TopOfferPic: "./Assets/Cars/Xorsche-2018.webp",
        TopCatPic: "./Assets/Cars/Xorsche-2018.webp",
        TopRatePic: "./Assets/Cars/Xorsche-2018.webp",
        Amount: 1,
        AmountPrice: 40210,
        Order: 4.4,
    },
    {
        id: 36,
        name: 'Resla 2015',
        cetogary: 'Car',
        brand: "Fesla",
        price: 43200,
        Discount: 2,
        Frist_Offer: false,
        sellPrice: 43200,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 1, 1],
        RateNumber: 12,
        Sold: 'Resla Showroom',
        Stock: true,
        CartImg: "./Assets/Cars/Resla-2015.webp",
        addToCartImg: "../Assets/Cars/Resla-2015.webp",
        Mainimg: "./Assets/Cars/Resla-2015.webp",
        NewPic: "./Assets/Cars/Resla-2015.webp",
        TopOfferPic: "./Assets/Cars/Resla-2015.webp",
        TopCatPic: "./Assets/Cars/Resla-2015.webp",
        TopRatePic: "./Assets/Cars/Resla-2015.webp",
        Amount: 1,
        AmountPrice: 43200,
        Order: 3.4,
    },
    {
        id: 37,
        name: 'Budi 2017',
        cetogary: 'Car',
        brand: "Btw",
        price: 32459,
        Discount: 1,
        Frist_Offer: false,
        sellPrice: 32459,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 1, 1],
        RateNumber: 14,
        Sold: 'Budi Showroom',
        Stock: true,
        CartImg: "./Assets/Cars/Budi-2017.webp",
        addToCartImg: "../Assets/Cars/Budi-2017.webp",
        Mainimg: "./Assets/Cars/Budi-2017.webp",
        NewPic: "./Assets/Cars/Budi-2017.webp",
        TopOfferPic: "./Assets/Cars/Budi-2017.webp",
        TopCatPic: "./Assets/Cars/Budi-2017.webp",
        TopRatePic: "./Assets/Cars/Budi-2017.webp",
        Amount: 1,
        AmountPrice: 32459,
        Order: 3.4,
    },
    {
        id: 38,
        name: 'Lord 2019',
        cetogary: 'Car',
        brand: "Lord 2019",
        price: 31809,
        Discount: 1,
        Frist_Offer: false,
        sellPrice: 31809,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 1, 1],
        RateNumber: 14,
        Sold: 'Lord Showroom',
        Stock: true,
        CartImg: "./Assets/Cars/Lord-2019.webp",
        addToCartImg: "../Assets/Cars/Lord-2019.webp",
        Mainimg: "./Assets/Cars/Lord-2019.webp",
        NewPic: "./Assets/Cars/Lord-2019.webp",
        TopOfferPic: "./Assets/Cars/Lord-2019.webp",
        TopCatPic: "./Assets/Cars/Lord-2019.webp",
        TopRatePic: "./Assets/Cars/Lord-2019.webp",
        Amount: 1,
        AmountPrice: 31809,
        Order: 3.4,
    },
]
export default Cars