const Mobile = [
    {
        id: 25,
        name: 'Mapple Earphones',
        cetogary: 'Mobile',
        brand: "Mapple",
        price: 890,
        Discount: 3,
        Frist_Offer: false,
        sellPrice: 890,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 1, 1],
        RateNumber: 12,
        Sold: 'Mapple',
        Stock: true,
        CartImg: "./Assets/Mobile/Mapple-Earphones.webp",
        Mainimg: "./Assets/Mobile/Mapple-Earphones.webp",
        NewPic: "./Assets/Mobile/Mapple-Earphones.webp",
        TopOfferPic: "./Assets/Mobile/Mapple-Earphones.webp",
        TopCatPic: "./Assets/Mobile/Mapple-Earphones.webp",
        TopRatePic: "./Assets/Mobile/Mapple-Earphones.webp",
        Amount: 1,
        AmountPrice: 890,
        Order: 4.4,
    },

    {
        id: 26,
        name: 'Silver-Cap',
        cetogary: 'cloth store',
        brand: "Silver-Cap",
        price: 13,
        Discount: 4,
        Frist_Offer: false,
        sellPrice: 13,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 1, 1],
        RateNumber: 12,
        Sold: 'Silver-Cap',
        Stock: true,
        CartImg: "./Assets/Mobile/Silver-Cap.webp",
        Mainimg: "./Assets/Mobile/Silver-Cap.webp",
        NewPic: "./Assets/Mobile/Silver-Cap.webp",
        TopOfferPic: "./Assets/Mobile/Silver-Cap.webp",
        TopCatPic: "./Assets/Mobile/Silver-Cap.webp",
        TopRatePic: "./Assets/Mobile/Silver-Cap.webp",
        Amount: 1,
        AmountPrice: 13,
        Order: 4.4,
    },
    {
        id: 27,
        name: 'earphones',
        cetogary: 'Mobile 0',
        brand: "earphones",
        price: 120,
        Discount: 7,
        Frist_Offer: false,
        sellPrice: 120,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 1, 0],
        RateNumber: 43,
        Sold: 'earphones',
        Stock: true,
        CartImg: "./Assets/Mobile/earphones.webp",
        Mainimg: "./Assets/Mobile/earphones.webp",
        NewPic: "./Assets/Mobile/earphones.webp",
        TopOfferPic: "./Assets/Mobile/earphones.webp",
        TopCatPic: "./Assets/Mobile/earphones.webp",
        TopRatePic: "./Assets/Mobile/earphones.webp",
        Amount: 1,
        AmountPrice: 120,
        Order: 8.4,
    },
    {
        id: 28,
        name: 'HPC-2018',
        cetogary: 'Mobile 0',
        brand: "HPC-2018",
        price: 239,
        Discount: 6,
        Frist_Offer: false,
        sellPrice: 239,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 0, 0],
        RateNumber: 79,
        Sold: 'HPC-2018',
        Stock: true,
        CartImg: "./Assets/Mobile/HPC-2018.webp",
        Mainimg: "./Assets/Mobile/HPC-2018.webp",
        NewPic: "./Assets/Mobile/HPC-2018.webp",
        TopOfferPic: "./Assets/Mobile/HPC-2018.webp",
        TopCatPic: "./Assets/Mobile/HPC-2018.webp",
        TopRatePic: "./Assets/Mobile/HPC-2018.webp",
        Amount: 1,
        AmountPrice: 239,
        Order: 1.4,
    },
    {
        id: 29,
        name: 'Ceats-wireless-earphones',
        cetogary: 'Mobile 0',
        brand: "Ceats-wireless-earphones",
        price: 450,
        Discount: 3,
        Frist_Offer: false,
        sellPrice: 450,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 1, 0],
        RateNumber: 12,
        Sold: 'Ceats-wireless-earphones',
        Stock: true,
        CartImg: "./Assets/Mobile/Ceats-wireless-earphones.webp",
        Mainimg: "./Assets/Mobile/Ceats-wireless-earphones.webp",
        NewPic: "./Assets/Mobile/Ceats-wireless-earphones.webp",
        TopOfferPic: "./Assets/Mobile/Ceats-wireless-earphones.webp",
        TopCatPic: "./Assets/Mobile/Ceats-wireless-earphones.webp",
        TopRatePic: "./Assets/Mobile/Ceats-wireless-earphones.webp",
        Amount: 1,
        AmountPrice: 450,
        Order: 1.4,
    },
    {
        id: 30,
        name: 'Lphone-7',
        cetogary: 'Mobile 0',
        brand: "Lphone-7",
        price: 123,
        Discount: 9,
        Frist_Offer: false,
        sellPrice: 123,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 1, 0],
        RateNumber: 12,
        Sold: 'Lphone-7',
        Stock: true,
        CartImg: "./Assets/Mobile/Lphone-7.webp",
        Mainimg: "./Assets/Mobile/Lphone-7.webp",
        NewPic: "./Assets/Mobile/Lphone-7.webp",
        TopOfferPic: "./Assets/Mobile/Lphone-7.webp",
        TopCatPic: "./Assets/Mobile/Lphone-7.webp",
        TopRatePic: "./Assets/Mobile/Lphone-7.webp",
        Amount: 1,
        AmountPrice: 123,
        Order: 1.4,
    },
    {
        id: 31,
        name: 'Xymphone-lights',
        cetogary: 'Mobile showroom',
        brand: "Xymphone-lights",
        price: 897,
        Discount: 9,
        Frist_Offer: false,
        sellPrice: 897,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 1, 1],
        RateNumber: 12,
        Sold: 'Xymphone-lights',
        Stock: true,
        CartImg: "./Assets/Mobile/Xymphone-lights.webp",
        Mainimg: "./Assets/Mobile/Xymphone-lights.webp",
        NewPic: "./Assets/Mobile/Xymphone-lights.webp",
        TopOfferPic: "./Assets/Mobile/Xymphone-lights.webp",
        TopCatPic: "./Assets/Mobile/Xymphone-lights.webp",
        TopRatePic: "./Assets/Mobile/Xymphone-lights.webp",
        Amount: 1,
        AmountPrice: 897,
        Order: 9.4,
    },
    {
        id: 32,
        name: 'Lokia-android-one',
        cetogary: 'Mobile showroom',
        brand: "Lokia-android-one",
        price: 908,
        Discount: 6,
        Frist_Offer: false,
        sellPrice: 908,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 1, 1],
        RateNumber: 12,
        Sold: 'Lokia-android-one',
        Stock: true,
        CartImg: "./Assets/Mobile/Lokia-android-one.webp",
        Mainimg: "./Assets/Mobile/Lokia-android-one.webp",
        NewPic: "./Assets/Mobile/Lokia-android-one.webp",
        TopOfferPic: "./Assets/Mobile/Lokia-android-one.webp",
        TopCatPic: "./Assets/Mobile/Lokia-android-one.webp",
        TopRatePic: "./Assets/Mobile/Lokia-android-one.webp",
        Amount: 1,
        AmountPrice: 908,
        Order: 9.4,
    },

]
export default Mobile