const NewProduct = [
    {
        id: 19,
        price: 50,
        name: 'Makeup',
        img: './assets/NewItem/makeup1.webp',
        Mainimg: './assets/NewItem/makeup1.webp',
        cetogary: 'Mobile',
        brand: "Mapple",
        Discount: 1,
        Frist_Offer: false,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 1, 0],
        RateNumber: 12,
        Sold: 'Mapple',
        Stock: true,
        NewPic: "./assets/NewItem/makeup1.webp",
        CartImg: "./assets/NewItem/makeup1.webp",
        addToCartImg: "../assets/NewItem/makeup1.webp",
        TopOfferPic: "./assets/NewItem/makeup1.webp",
        TopCatPic: "./assets/NewItem/makeup1.webp",
        TopRatePic: "./assets/NewItem/makeup1.webp",
        Amount: 1,
        AmountPrice: 50,
        Order: 4.4,
    },
    {
        id: 20,
        price: 30,
        name: 'Smart Watch',
        img: './assets/NewItem/makeup2.webp',
        Mainimg: './assets/NewItem/makeup2.webp',
        cetogary: 'Mobile',
        brand: "Mapple",
        Discount: 1,
        Frist_Offer: false,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 1, 0],
        RateNumber: 12,
        Sold: 'Mapple',
        Stock: true,
        NewPic: './assets/NewItem/makeup2.webp',
        CartImg: './assets/NewItem/makeup2.webp',
        addToCartImg: '../assets/NewItem/makeup2.webp',
        TopOfferPic: './assets/NewItem/makeup2.webp',
        TopCatPic: './assets/NewItem/makeup2.webp',
        TopRatePic: './assets/NewItem/makeup2.webp',
        Amount: 1,
        AmountPrice: 30,
        Order: 4.4,
    },
    {
        id: 21,
        price: 140,
        name: 'Lipstick',
        img: './assets/NewItem/makeup3.webp',
        Mainimg: './assets/NewItem/makeup3.webp',
        cetogary: 'Mobile',
        brand: "Mapple",
        Discount: 1,
        Frist_Offer: false,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 1, 0],
        RateNumber: 12,
        Sold: 'Mapple',
        Stock: true,
        NewPic: './assets/NewItem/makeup3.webp',
        CartImg: './assets/NewItem/makeup3.webp',
        addToCartImg: '../assets/NewItem/makeup3.webp',
        TopOfferPic: './assets/NewItem/makeup3.webp',
        TopCatPic: './assets/NewItem/makeup3.webp',
        TopRatePic: './assets/NewItem/makeup3.webp',
        Amount: 1,
        AmountPrice: 140,
        Order: 4.4,
    },
    {
        id: 22,
        price: 243,
        name: 'Green plant',
        img: './assets/NewItem/makeup4.webp',
        Mainimg: './assets/NewItem/makeup4.webp',
        cetogary: 'Mobile',
        brand: "Mapple",
        Discount: 1,
        Frist_Offer: false,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 1, 0],
        RateNumber: 12,
        Sold: 'Mapple',
        Stock: true,
        NewPic: './assets/NewItem/makeup4.webp',
        CartImg: './assets/NewItem/makeup4.webp',
        addToCartImg: '../assets/NewItem/makeup4.webp',
        TopOfferPic: './assets/NewItem/makeup4.webp',
        TopCatPic: './assets/NewItem/makeup4.webp',
        TopRatePic: './assets/NewItem/makeup4.webp',
        Amount: 1,
        AmountPrice: 243,
        Order: 4.4,
    },
    {
        id: 23,
        price: 140,
        name: 'Bonsai tree',
        img: './assets/NewItem/plant.webp',
        Mainimg: './assets/NewItem/plant.webp',
        cetogary: 'Mobile',
        brand: "Mapple",
        Discount: 1,
        Frist_Offer: false,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 1, 0],
        RateNumber: 12,
        Sold: 'Mapple',
        Stock: true,
        NewPic: './assets/NewItem/plant.webp',
        CartImg: './assets/NewItem/plant.webp',
        addToCartImg: '../assets/NewItem/plant.webp',
        TopOfferPic: './assets/NewItem/plant.webp',
        TopCatPic: './assets/NewItem/plant.webp',
        TopRatePic: './assets/NewItem/plant.webp',
        Amount: 1,
        AmountPrice: 140,
        Order: 4.4,
    },
    {
        id: 24,
        price: 140,
        name: 'Sunglass',
        img: './assets/NewItem/sunglass.webp',
        Mainimg: './assets/NewItem/sunglass.webp',
        cetogary: 'Mobile',
        brand: "Mapple",
        Discount: 1,
        Frist_Offer: false,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 1, 0],
        RateNumber: 12,
        Sold: 'Mapple',
        Stock: true,
        NewPic: './assets/NewItem/sunglass.webp',
        CartImg: './assets/NewItem/sunglass.webp',
        addToCartImg: '../assets/NewItem/sunglass.webp',
        TopOfferPic: './assets/NewItem/sunglass.webp',
        TopCatPic: './assets/NewItem/sunglass.webp',
        TopRatePic: './assets/NewItem/sunglass.webp',
        Amount: 1,
        AmountPrice: 140,
        Order: 4.4,
    },
]
export default NewProduct