const Prodect = [
    {
        id: 1,
        name: 'Xeats bluetooth earphones',
        brand: "Xeats",
        price: 187,
        Discount: 45,
        Frist_Offer: false,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 1, 0],
        RateNumber: 41,
        Sold: 'Mobile Store',
        Stock: true,
        CartImg: "./Assets/item/Xeats.webp",
        addToCartImg: "../Assets/item/Xeats.webp",
        Mainimg: "./Assets/item/Xeats1.png",
        NewPic: "./Assets/item/Xeats.webp",
        TopOfferPic: "./Assets/item/Xeats.webp",
        TopCatPic: "./Assets/item/Xeats.webp",
        TopRatePic: "./Assets/item/Xeats.webp",
        Amount: 1,
        AmountPrice: 187,
        Order: 10,
    },
    {
        id: 2,
        name: 'Smart Watch Black',
        brand: "Ziaomi",
        price: 100,
        Discount: 14,
        Frist_Offer: false,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 1, 0],
        RateNumber: 49,
        Sold: 'Watch Store',
        Stock: true,
        CartImg: "./Assets/item/watch3.webp",
        addToCartImg: "../Assets/item/watch3.webp",
        Mainimg: "./Assets/item/watch3.png",
        NewPic: "./Assets/item/watch3.webp",
        TopOfferPic: "./Assets/item/watch3.webp",
        TopCatPic: "./Assets/item/watch3.webp",
        TopRatePic: "./Assets/item/watch3.webp",
        Amount: 1,
        AmountPrice: 50,
        Order: 10,
    },
    {
        id: 3,
        name: 'sbs Wireless Earphones',
        brand: "Ziaomi",
        price: 190,
        Discount: 35,
        Frist_Offer: false,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 0, 0],
        RateNumber: 49,
        Sold: 'Mobile Store',
        Stock: true,
        CartImg: "./Assets/item/sbs.webp",
        addToCartImg: "../Assets/item/sbs.webp",
        Mainimg: "./Assets/item/sbs1.png",
        NewPic: "./Assets/item/sbs.webp",
        TopOfferPic: "./Assets/item/sbs.webp",
        TopCatPic: "./Assets/item/sbs.webp",
        TopRatePic: "./Assets/item/sbs.webp",
        Amount: 1,
        AmountPrice: 190,
        Order: 10,
    },
    {
        id: 4,
        name: 'Watch',
        brand: "XMI",
        price: 4,
        Discount: 39,
        Frist_Offer: false,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 1, 1],
        RateNumber: 49,
        Sold: 'Mobile Store',
        Stock: false,
        CartImg: "./Assets/item/watchXmi.webp",
        addToCartImg: "../Assets/item/watchXmi.webp",
        Mainimg: "./Assets/item/watchXmi1.png",
        NewPic: "./Assets/item/watchXmi.webp",
        TopOfferPic: "./Assets/item/watchXmi.webp",
        TopCatPic: "./Assets/item/watchXmi.webp",
        TopRatePic: "./Assets/item/watchXmi.webp",
        Amount: 1,
        AmountPrice: 4,
        Order: 10,
    },
    {
        id: 5,
        name: 'Mi Phone',
        brand: "Xeats",
        price: 302,
        Discount: 14,
        Frist_Offer: false,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 1, 1],
        RateNumber: 49,
        Sold: 'Mobile Store',
        Stock: true,
        CartImg: "./Assets/item/phone.webp",
        addToCartImg: "../Assets/item/phone.webp",
        Mainimg: "./Assets/item/phone.webp",
        NewPic: "./Assets/item/phone.webp",
        TopOfferPic: "./Assets/item/phone.webp",
        TopCatPic: "./Assets/item/phone.webp",
        TopRatePic: "./Assets/item/phone.webp",
        Amount: 1,
        AmountPrice: 302,
        Order: 10,
    },
    {
        id: 6,
        name: 'Smart Watch Black',
        brand: "Ziaomi",
        price: 50,
        Discount: 37,
        Frist_Offer: false,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 1, 1],
        RateNumber: 49,
        Sold: 'Watch Store',
        Stock: true,
        CartImg: "./Assets/item/watch3.webp",
        addToCartImg: "../Assets/item/watch3.webp",
        Mainimg: "./Assets/item/watch3.webp",
        NewPic: "./Assets/item/watch3.webp",
        TopOfferPic: "./Assets/item/watch3.webp",
        TopCatPic: "./Assets/topCat/watch3.webp",
        TopRatePic: "./Assets/item/watch3.webp",
        Amount: 1,
        AmountPrice: 50,
        Order: 67.3,
    },
    {
        id: 7,
        name: 'sbs Wireless Earphones',
        brand: "Ziaomi",
        price: 190,
        Discount: 45,
        Frist_Offer: false,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 0, 0],
        RateNumber: 49,
        Sold: 'Mobile Store',
        Stock: true,
        CartImg: "./Assets/item/sbs.webp",
        addToCartImg: "../Assets/item/sbs.webp",
        Mainimg: "./Assets/item/sbs1.png",
        NewPic: "./Assets/item/sbs.webp",
        TopOfferPic: "./Assets/item/sbs.webp",
        TopCatPic: "./Assets/item/sbs.webp",
        TopRatePic: "./Assets/item/sbs.webp",
        Amount: 1,
        AmountPrice: 190,
        Order: 10,
    },
    {
        id: 8,
        name: 'Black shoes',
        brand: "shoesPI",
        price: 6,
        Discount: 50,
        Frist_Offer: true,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 1, 1],
        RateNumber: 49,
        Sold: 'shoes shop',
        Stock: true,
        CartImg: "./Assets/item/shoes.webp",
        addToCartImg: "../Assets/item/shoes.webp",
        Mainimg: "./Assets/item/shoes.webp",
        NewPic: "./Assets/item/shoes.webp",
        TopOfferPic: "./Assets/TopOffer/shoes.png",
        TopCatPic: "./Assets/item/shoes.webp",
        TopRatePic: "./Assets/item/shoes.webp",
        Amount: 1,
        AmountPrice: 6,
        Order: 10,
    },
    {
        id: 9,
        name: 'sbs Wireless Headphone',
        brand: "Ziaomi",
        price: 190,
        Discount: 50,
        Frist_Offer: true,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 0, 0],
        RateNumber: 49,
        Sold: 'Mobile Store',
        Stock: true,
        CartImg: "./Assets/item/Headphone.png",
        addToCartImg: "../Assets/item/Headphone.png",
        Mainimg: "./Assets/item/headphone1.png",
        NewPic: "./Assets/item/Headphone.png",
        TopOfferPic: "./Assets/TopOffer/Headphone.png",
        TopCatPic: "./Assets/topCat/Headphone.webp",
        TopRatePic: "./Assets/item/Headphone.png",
        Amount: 1,
        AmountPrice: 190,
        Order: 30.1,
    },
    {
        id: 10,
        name: 'Smart Watch White',
        brand: "Ziaomi",
        price: 50,
        Discount: 49,
        Frist_Offer: true,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 1, 0],
        RateNumber: 49,
        Sold: 'Watch Store',
        Stock: true,
        CartImg: "./Assets/item/watch1.png",
        addToCartImg: "../Assets/item/watch1.png",
        Mainimg: "./Assets/item/watch1.png",
        NewPic: "./Assets/item/watch1.png",
        TopOfferPic: "./Assets/TopOffer/watch.png",
        TopCatPic: "./Assets/item/watch1.png",
        TopRatePic: "./Assets/item/watch1.png",
        Amount: 1,
        AmountPrice: 50,
        Order: 10,
    },
    {
        id: 11,
        name: 'Ray Ban Sunglass',
        brand: "Ray Ban",
        price: 10,
        Discount: 20,
        Frist_Offer: true,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 1, 0],
        RateNumber: 120,
        Sold: 'Ray Ban Store',
        Stock: true,
        CartImg: "./Assets/item/ray-ban-galss.png",
        addToCartImg: "../Assets/item/ray-ban-galss.png",
        Mainimg: "./Assets/item/ray-ban-galss.png",
        NewPic: "./Assets/item/ray-ban-galss.png",
        TopOfferPic: "./Assets/TopOffer/ray_ban_01.png",
        TopCatPic: "./Assets/topCat/ray_ban_01.webp",
        TopRatePic: "./Assets/item/ray_ban_01.jpg",
        Amount: 1,
        AmountPrice: 10,
        Order: 90.4,
    },
    {
        id: 12,
        name: 'BenX 2020',
        brand: "BenX-2020",
        price: 250,
        Discount: 56,
        Frist_Offer: false,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 0, 0],
        RateNumber: 12,
        Sold: 'Mobile Store',
        Stock: true,
        CartImg: "./Assets/item/BenX2020.webp",
        addToCartImg: "../Assets/item/BenX2020.webp",
        Mainimg: "./Assets/item/BenX2020.webp",
        NewPic: "./Assets/item/BenX2020.webp",
        TopOfferPic: "./Assets/item/BenX2020.webp",
        TopCatPic: "./Assets/item/BenX2020.webp",
        TopRatePic: "./Assets/item/BenX2020.webp",
        Amount: 1,
        AmountPrice: 250,
        Order: 10.4,
    },
    {
        id: 13,
        name: 'pune HD',
        brand: "pune HD",
        price: 450,
        Discount: 56,
        Frist_Offer: false,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 0, 0],
        RateNumber: 12,
        Sold: 'Gaming Store',
        Stock: true,
        CartImg: "./Assets/item/pune.webp",
        addToCartImg: "../Assets/item/pune.webp",
        Mainimg: "./Assets/item/pune.webp",
        NewPic: "./Assets/item/pune.webp",
        TopOfferPic: "./Assets/item/pune.webp",
        TopCatPic: "./Assets/item/pune.webp",
        TopRatePic: "./Assets/item/pune.webp",
        Amount: 1,
        AmountPrice: 450,
        Order: 4.4,
    },
    {
        id: 14,
        name: 'ranasonic',
        brand: "ranasonic",
        price: 250,
        Discount: 66,
        Frist_Offer: false,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 0, 0],
        RateNumber: 12,
        Sold: 'Gaming Store',
        Stock: true,
        CartImg: "./Assets/item/ranasonic.webp",
        addToCartImg: "../Assets/item/ranasonic.webp",
        Mainimg: "./Assets/item/ranasonic.webp",
        NewPic: "./Assets/item/ranasonic.webp",
        TopOfferPic: "./Assets/item/ranasonic.webp",
        TopCatPic: "./Assets/item/ranasonic.webp",
        TopRatePic: "./Assets/item/ranasonic.webp",
        Amount: 1,
        AmountPrice: 250,
        Order: 4.4,
    },
    {
        id: 15,
        name: 'RG Product',
        brand: "RG Product",
        price: 500,
        Discount: 60,
        Frist_Offer: false,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 0, 0],
        RateNumber: 12,
        Sold: 'RG Product Store',
        Stock: true,
        CartImg: "./Assets/item/RG.webp",
        addToCartImg: "../Assets/item/RG.webp",
        Mainimg: "./Assets/item/RG.webp",
        NewPic: "./Assets/item/RG.webp",
        TopOfferPic: "./Assets/item/RG.webp",
        TopCatPic: "./Assets/item/RG.webp",
        TopRatePic: "./Assets/item/RG.webp",
        Amount: 1,
        AmountPrice: 500,
        Order: 4.4,
    },
    {
        id: 16,
        name: 'SetGears',
        brand: "SetGears",
        price: 670,
        Discount: 71,
        Frist_Offer: false,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 0, 0],
        RateNumber: 12,
        Sold: 'SetGears Store',
        Stock: true,
        CartImg: "./Assets/item/SetGears.webp",
        addToCartImg: "../Assets/item/SetGears.webp",
        Mainimg: "./Assets/item/SetGears.webp",
        NewPic: "./Assets/item/SetGears.webp",
        TopOfferPic: "./Assets/item/SetGears.webp",
        TopCatPic: "./Assets/item/SetGears.webp",
        TopRatePic: "./Assets/item/SetGears.webp",
        Amount: 1,
        AmountPrice: 670,
        Order: 4.4,
    },
    {
        id: 17,
        name: 'SonyTV',
        brand: "SonyTV",
        price: 451,
        Discount: 61,
        Frist_Offer: false,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 0, 0],
        RateNumber: 12,
        Sold: 'Sony Store',
        Stock: true,
        CartImg: "./Assets/item/SonyTV.webp",
        addToCartImg: "../Assets/item/SonyTV.webp",
        Mainimg: "./Assets/item/SonyTV.webp",
        NewPic: "./Assets/item/SonyTV.webp",
        TopOfferPic: "./Assets/item/SonyTV.webp",
        TopCatPic: "./Assets/item/SonyTV.webp",
        TopRatePic: "./Assets/item/SonyTV.webp",
        Amount: 1,
        AmountPrice: 451,
        Order: 4.4,
    },
    {
        id: 18,
        name: 'tony CCTV',
        brand: "tony CCTV",
        price: 380,
        Discount: 51,
        Frist_Offer: false,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 0, 0],
        RateNumber: 12,
        Sold: 'Tony Store',
        Stock: true,
        CartImg: "./Assets/item/tonyCCTV.webp",
        addToCartImg: "../Assets/item/tonyCCTV.webp",
        Mainimg: "./Assets/item/tonyCCTV.webp",
        NewPic: "./Assets/item/tonyCCTV.webp",
        TopOfferPic: "./Assets/item/tonyCCTV.webp",
        TopCatPic: "./Assets/item/tonyCCTV.webp",
        TopRatePic: "./Assets/item/tonyCCTV.webp",
        Amount: 1,
        AmountPrice: 380,
        Order: 4.4,
    },
    {
        id: 18,
        name: 'Tony PS4',
        brand: "Tony PS4",
        price: 380,
        Discount: 67,
        Frist_Offer: false,
        detaile: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et eos veniam quia ex numquam hic ",
        star: [1, 1, 1, 0, 0],
        RateNumber: 12,
        Sold: 'Tony gaming Store',
        Stock: true,
        CartImg: "./Assets/item/TonyPS4.webp",
        addToCartImg: "../Assets/item/TonyPS4.webp",
        Mainimg: "./Assets/item/TonyPS4.webp",
        NewPic: "./Assets/item/TonyPS4.webp",
        TopOfferPic: "./Assets/item/TonyPS4.webp",
        TopCatPic: "./Assets/item/TonyPS4.webp",
        TopRatePic: "./Assets/item/TonyPS4.webp",
        Amount: 1,
        AmountPrice: 380,
        Order: 4.4,
    },

];
export default Prodect