const TopOrder = [
    {
        id: 1,
        name: 'Headphone',
        brand: "Mibile Shop",
        price: 12,
        AmountPrice: 12,
        star: [1, 1, 1, 1, 1],
        Sold: 'Mi Store',
        Stock: true,
        img1: "assets/topCat/Top1.webp",
        img: 'assets/item/35.webp',
        Amount: 1,
        order: 30.1,
    },

    {
        id: 2,
        name: 'Glass',
        brand: "Glass Shop",
        price: 9,
        AmountPrice: 9,
        star: [1, 1, 1, 1, 1],
        Sold: 'Glass Store',
        Stock: true,
        img1: "assets/topCat/Top2.webp",
        img: 'assets/item/35.webp',
        Amount: 1,
        order: 41.3,
    },

    {
        id: 3,
        name: 'Watch',
        brand: "Watch Shop",
        price: 9,
        AmountPrice: 9,
        star: [1, 1, 1, 1, 1],
        Sold: 'Watch Store',
        Stock: true,
        img1: "assets/topCat/Top3.webp",
        img: 'assets/item/35.webp',
        Amount: 1,
        order: 29.3,
    },
    {
        id: 5,
        name: 'Glass',
        brand: "Glass Shop",
        price: 9,
        AmountPrice: 9,
        star: [1, 1, 1, 1, 1],
        Sold: 'Glass Store',
        Stock: true,
        img1: "assets/topCat/Top2.webp",
        img: 'assets/item/35.webp',
        Amount: 1,
        order: 41.3,
    },

    {
        id: 6,
        name: 'Watch',
        brand: "Watch Shop",
        price: 9,
        AmountPrice: 9,
        star: [1, 1, 1, 1, 1],
        Sold: 'Watch Store',
        Stock: true,
        img1: "assets/topCat/Top3.webp",
        img: 'assets/item/35.webp',
        Amount: 1,
        order: 29.3,
    },
    {
        id: 4,
        name: 'Headphone',
        brand: "Mibile Shop",
        price: 12,
        AmountPrice: 12,
        star: [1, 1, 1, 1, 1],
        Sold: 'Mi Store',
        Stock: true,
        img1: "assets/topCat/Top1.webp",
        img: 'assets/item/35.webp',
        Amount: 1,
        order: 30.1,
    },


]

export default TopOrder